### ISSUE TITLE
[AVM Module Issue]: ID of Output "resource" returns null when trying to pass into another module

### ISSUE THREAD

**Issue by philipstreet** [Azure/terraform-azurerm-avm-res-network-firewallpolicy#16]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.0

### Description

Example code to replicate issue.

```
# This picks a random region from the list of regions.
resource "random_integer" "region_index" {
  min = 0
  max = length(local.azure_regions) - 1
}

# This ensures we have unique CAF compliant names for our resources.
module "naming" {
  source  = "Azure/naming/azurerm"
  version = "0.3.0"
}
resource "azurerm_resource_group" "rg" {
  name = "rg-test"
  location = "uksouth"
}

module "firewall_policy" {
  source = "Azure/avm-res-network-firewallpolicy/azurerm"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  name                =  module.naming.firewall_policy.name
}

resource "azurerm_virtual_network" "vnet" {
  name                = module.naming.virtual_network.name
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  address_space       = ["10.1.0.0/16"]
}
resource "azurerm_subnet" "subnet" {
  name                 = "AzureFirewallSubnet"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes     = ["10.1.0.0/26"]
}

resource "azurerm_public_ip" "public_ip" {
  name                = module.naming.public_ip.name
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  allocation_method   = "Static"
  sku                 = "Standard"
  zones               = ["1", "2", "3"]
}

# This is the module call
module "firewall" {
  source             = "Azure/avm-res-network-firewall/azurerm"
  name                = module.naming.firewall.name
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  firewall_policy_id = module.firewall_policy.resource.id
  firewall_sku_tier   = "Premium"
  firewall_sku_name   = "AZFW_VNet"
  firewall_zones      = ["1", "2", "3"]
  firewall_ip_configuration = [
    {
      name                 = "ipconfig1"
      subnet_id            = azurerm_subnet.subnet.id
      public_ip_address_id = azurerm_public_ip.public_ip.id
    }
  ]
}
```

Expected behaviour: Firewall Policy is created and the resource ID is returned and set on the Azure Firewall.
Actual behaviour: Firewall Policy is created but the resource ID returned is null so is not associated with the Azure Firewall.

Question: Am I doing this right? Is there something I should be doing to force the resource ID to be returned?

**Comment by cshea-msft** [comment]
@philipstreet That looks good. Is the Firewall Policy not attached to your Firewall? If you do a terraform apply && terraform show you should see the output of the resource IDs once the deployment is completed.

**Comment by philipstreet** [comment]
@cshea-msft Correct. Both the Firewall and Firewall Policy resources are being deployed but somehow the ID of the Firewall Policy is not being passed to or set on the Firewall. Even on subsequent runs (after both resources are deployed), the Firewall Policy ID is not being detected and passed to the Firewall.

Full disclosure: This is not the exact code we are using, as we are actually trying to deploy Azure Firewalls as part of a secure hub in a Azure Virtual WAN using the avm-ptn-virtualwan module.

**Comment by cshea-msft** [comment]
Oh I think the Firewall Policy is defaulting to Standard and you are deploying a Premium Firewall. Can you put in the firewall_policy_sku variable and set it to Premium?

**Comment by philipstreet** [comment]
@cshea-msft Yeah, we're currently setting the Firewall SKU as "Standard". Here's the actual "firewalls" block from our VWAN module code;

``` hcl
  firewalls = {
    (local.firewall_name_001) = {
      sku_name           = "AZFW_Hub"
      sku_tier           = "Standard"
      name               = local.firewall_name_001
      virtual_hub_key    = local.virtual_hub_name_001
      firewall_policy_id = module.firewall_policy.resource.id
      tags               = local.tags
    }
    (local.firewall_name_002) = {
      sku_name           = "AZFW_Hub"
      sku_tier           = "Standard"
      name               = local.firewall_name_002
      virtual_hub_key    = local.virtual_hub_name_002
      firewall_policy_id = module.firewall_policy.resource.id
      tags               = local.tags
    }
  }
```

I'll try it now with Premium.

**Comment by philipstreet** [comment]
@cshea-msft I think I've found why the Policy is not being set on the Firewall...

...because the module does not set it anywhere. :-)

The _firewall.tf_ file does not set the firewall_policy_id attribute passed in by the _firewalls_ variable, and it is not being set elsewhere.

Additionally, if you look at the variable _firewalls_ object definition, there are a bunch of attributes defined that are not being set at all, e.g. _dns_servers_, _threat_intel_mode_. 

I'm unsure whether some of the attributes are being deliberately omitted as they are not relevant for an Azure Firewall deployed in a Virtual WAN hub, e.g. _management_ip_configuration_, so.

**Comment by cshea-msft** [comment]
@philipstreet can you tag me in that issue so i can stay in the loop. I can make changes on myside with the vwan example if needed.
