### ISSUE TITLE
[AVM Module Issue]: Missing modtm in required providers

### ISSUE THREAD

**Issue by jchancellor-ms** [Azure/terraform-azurerm-avm-res-network-firewallpolicy#40]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.2.2

### Description

When deploying inside another module I get the following error:  

Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/modtm: provider registry registry.terraform.io does not have a provider named
│ registry.terraform.io/hashicorp/modtm
│
│ Did you intend to use azure/modtm? If so, you must specify that source address in each module which requires that provider. To see which modules are currently depending on
│ hashicorp/modtm, run the following command:
│     terraform providers

**Comment by cshea-msft** [comment]
Thanks @jchancellor-ms i believe this is an issue with the new push from the Core team. Will investigate it.

**Comment by cshea-msft** [comment]
this was fixed in latest version
